# Generated by Django 4.2.7 on 2023-11-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('address', models.CharField(max_length=60, verbose_name='Address')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('email_address', models.EmailField(max_length=20, verbose_name='Email Address')),
            ],
        ),
    ]
