# Generated by Django 4.2.7 on 2023-11-17 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ref_id',
            field=models.CharField(default=uuid.uuid4, max_length=10, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email_address',
            field=models.EmailField(max_length=40, verbose_name='Email Address'),
        ),
    ]
