# Generated by Django 4.2.7 on 2023-11-17 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0002_registration_ref_id_alter_registration_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_caption', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='ref_id',
            field=models.CharField(default=uuid.uuid4, max_length=8, verbose_name='Reference No.'),
        ),
    ]
