# Generated by Django 4.2.7 on 2023-11-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
