# Generated by Django 4.2.7 on 2023-11-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letter', '0005_registration_registered_on_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_caption', models.CharField(max_length=8)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
